name: dinesh_portfolio
description: 'Dinesh Personal Portfolio'
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' 
dependencies:
  flutter:
    sdk: flutter 
  cupertino_icons: ^1.0.5
  google_fonts: ^5.1.0 
  injectable: ^2.3.2
  get_it: ^7.6.4
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  cloud_firestore: ^4.9.3
  firebase_core: ^2.17.0
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  gradient_circular_progress_indicator: ^0.0.4
  footer: ^0.0.4
  flutter_social_button: ^1.1.4+1
  url_launcher: ^6.1.14
  social_login_buttons: ^1.0.7
  social_media_buttons: ^1.0.0
  firebase_crashlytics: ^3.4.1
  flutter_device_type: ^0.4.0
  animated_text_kit: ^4.2.2
  auto_size_text: ^3.0.0
  flutter_svg: ^2.0.7
  cached_network_image: ^3.3.0
 
dev_dependencies:
  flutter_test:
    sdk: flutter 
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  injectable_generator: ^2.4.1
  freezed: ^2.4.5
  json_serializable: ^6.7.1
 
flutter:
  uses-material-design: true
  assets:
    - assets/